
# Training params
lr: 1.e-4  # learning rate
iter_collect: 20  # Collect results every _ iterations
max_iters: 200000

# Tensorboard stuff
tb_directory: joint_split_delete_training
flush_secs: 10  # Write tensorboard results every _ seconds

trainable_layer_names:  # for ResNet50+FPN
    - body.conv1.weight
    - body.layer1.0

# Loss function stuff
lambda_split: 0.
lambda_boundary: 1.0

# Padding stuff
padding_config:
    inference: False
    padding_alpha: 1.0
    padding_beta: 4.0
    min_padding_percentage: 0.05
    new_H: 64
    new_W: 64

# Starting optimization from previous checkpoint
load: False
iter_num: 200000  # Used only if load = True